FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG VITE_API_URL=/api
ENV VITE_API_URL=${VITE_API_URL}

RUN npm run build

FROM alpine:3.20

RUN mkdir -p /srv/frontend

COPY --from=build /app/dist /dist

CMD ["sh", "-c", "rm -rf /srv/frontend/* && cp -a /dist/. /srv/frontend"]
