# Generated by Django 4.2.30 on 2026-04-20 17:13

from django.db import migrations, models
import invoices.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(upload_to=invoices.models.invoice_upload_path, verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha emisión'),
        ),
    ]
