# Generated by Django 4.2.30 on 2026-04-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_alter_invoice_file_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio unitario'),
        ),
    ]
