# Generated by Django 4.2.30 on 2026-04-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoiceitem_total_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Margen de ganancia general (%)'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Ganancia (%)'),
        ),
    ]
