# Generated by Django 4.2.30 on 2026-04-28 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_invoice_file_binary_storage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='file',
        ),
    ]
