# Generated by Django 4.2.30 on 2026-04-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_user_id_ebcfda_idx',
            old_name='invoices_i_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_provide_0cb0d3_idx',
            old_name='invoices_i_provider_issue_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_user_id_eeb8b4_idx',
            old_name='invoices_i_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='invoice',
            new_name='invoices_in_status_874ef9_idx',
            old_name='invoices_i_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceitem',
            new_name='invoices_in_invoice_9d954a_idx',
            old_name='invoices_i_invoice_product_idx',
        ),
        migrations.RenameIndex(
            model_name='invoiceitem',
            new_name='invoices_in_product_e6d911_idx',
            old_name='invoices_i_product_price_idx',
        ),
    ]
