# Generated by Django 4.2.30 on 2026-05-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='priceitem',
            new_name='prices_pric_user_id_4b1f78_idx',
            old_name='prices_pric_user_id_order_idx',
        ),
        migrations.RenameIndex(
            model_name='pricesubitem',
            new_name='prices_pric_item_id_6ca2c8_idx',
            old_name='prices_pric_item_id_sub_idx',
        ),
    ]
