# Generated by Django 4.2.30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Fecha')),
                ('detail', models.CharField(max_length=500, verbose_name='Detalle')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Total')),
                ('document_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='N° Documento')),
                ('document_type', models.CharField(blank=True, choices=[('boleta', 'Boleta'), ('factura', 'Factura'), ('recibo', 'Recibo'), ('voucher', 'Voucher'), ('otro', 'Otro')], max_length=20, null=True, verbose_name='Tipo Documento')),
                ('provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Proveedor')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('file_data', models.BinaryField(blank=True, null=True, verbose_name='Datos del archivo')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre original')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo archivo')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['-date', '-created_at'], name='expenses_ex_date_d4f3a7_idx'), models.Index(fields=['document_type'], name='expenses_ex_documen_8b2c1e_idx')],
            },
        ),
    ]
