# Generated by Django 4.2.30 on 2026-05-25 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_add_is_company_invoice'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_date_840b41_idx',
            old_name='expenses_ex_date_d4f3a7_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_documen_a40749_idx',
            old_name='expenses_ex_documen_8b2c1e_idx',
        ),
    ]
