# Generated by Django 4.2.30 on 2026-04-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='providerinventory',
            new_name='provider_in_product_23c9e0_idx',
            old_name='provider_in_product_provider_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventory',
            new_name='provider_in_provide_6cbdcf_idx',
            old_name='provider_in_provider_stock_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventory',
            new_name='provider_in_product_d83e5c_idx',
            old_name='provider_in_product_name_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventory',
            new_name='provider_in_last_up_aaf1d6_idx',
            old_name='provider_in_last_updated_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventoryauditlog',
            new_name='provider_in_invento_092e31_idx',
            old_name='provider_in_inventory_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventoryauditlog',
            new_name='provider_in_source_ddce40_idx',
            old_name='provider_in_source_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventoryauditlog',
            new_name='provider_in_user_id_f84e1d_idx',
            old_name='provider_in_user_timestamp_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventoryauditlog',
            new_name='provider_in_invoice_5ea8e6_idx',
            old_name='provider_in_invoice_id_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventoryauditlog',
            new_name='provider_in_quote_i_c21546_idx',
            old_name='provider_in_quote_id_idx',
        ),
        migrations.RenameIndex(
            model_name='providerinventorypricehistory',
            new_name='provider_in_invento_c0d9b7_idx',
            old_name='provider_in_inventory_recorded_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='provider_in_quote_i_de1d6c_idx',
            old_name='provider_in_quote_status_idx',
        ),
        migrations.RenameIndex(
            model_name='stockreservation',
            new_name='provider_in_invento_1fd97b_idx',
            old_name='provider_in_inventory_status_idx',
        ),
    ]
