# Generated by Django 4.2.30 on 2026-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_inventory', '0002_rename_provider_in_product_provider_idx_provider_in_product_23c9e0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providerinventory',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cantidad disponible del producto', max_digits=12, verbose_name='Cantidad en stock'),
        ),
        migrations.AlterField(
            model_name='providerinventoryauditlog',
            name='quantity_after',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad después'),
        ),
        migrations.AlterField(
            model_name='providerinventoryauditlog',
            name='quantity_before',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad antes'),
        ),
        migrations.AlterField(
            model_name='providerinventoryauditlog',
            name='quantity_changed',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad cambiada'),
        ),
        migrations.AlterField(
            model_name='stockreservation',
            name='quantity_reserved',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad reservada'),
        ),
    ]
