# Generated by Django 4.2.30 on 2026-04-29 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_inventory', '0003_change_quantity_to_2_decimals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockreservation',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='stockreservation',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='stockreservation',
            name='quote_item',
        ),
        migrations.AlterField(
            model_name='providerinventory',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad en stock'),
        ),
        migrations.DeleteModel(
            name='ProviderInventoryPriceHistory',
        ),
        migrations.DeleteModel(
            name='StockReservation',
        ),
    ]
