# Generated by Django 4.2.30 on 2026-05-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_inventory', '0005_providerinventory_minimum_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinventory',
            name='markup_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de margen sobre el precio de compra', max_digits=5, verbose_name='Margen de ganancia (%)'),
        ),
    ]
