# Generated by Codex on 2026-05-26

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('provider_inventory', '0006_add_markup_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerinventoryauditlog',
            name='invoice_item_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Ítem Factura'),
        ),
        migrations.AddIndex(
            model_name='providerinventoryauditlog',
            index=models.Index(fields=['invoice_item_id'], name='provider_in_invoice_65082a_idx'),
        ),
        migrations.AddConstraint(
            model_name='providerinventoryauditlog',
            constraint=models.UniqueConstraint(
                condition=Q(invoice_item_id__isnull=False),
                fields=('inventory', 'source', 'invoice_item_id'),
                name='unique_inventory_invoice_item_audit',
            ),
        ),
    ]
