# Generated by Django 4.2.30 on 2026-04-29 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_add_provider_inventory_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='quote',
            new_name='quotes_quot_user_id_4defd9_idx',
            old_name='quotes_quot_user_id_status_idx',
        ),
        migrations.RenameIndex(
            model_name='quote',
            new_name='quotes_quot_user_id_eaa78b_idx',
            old_name='quotes_quot_user_id_created_at_idx',
        ),
    ]
