# Generated by Django 4.2.30 on 2026-04-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_rename_quotes_quot_user_id_status_idx_quotes_quot_user_id_4defd9_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
