# Generated by Django 4.2.30 on 2026-05-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_change_quantity_to_2_decimals'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo_data',
            field=models.BinaryField(blank=True, null=True, verbose_name='Logo (binario)'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo_mime',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='MIME del logo'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='logo_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Tamaño del logo (bytes)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo_base64',
            field=models.TextField(blank=True, default='', verbose_name='Logo legacy (base64)'),
        ),
    ]
