# Generated by Django 4.2.30 on 2026-05-07 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('quotes', '0006_migrate_logo_to_binary'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='clients.client', verbose_name='Cliente'),
        ),
    ]
