# Generated by Django 4.2.30 on 2026-04-29 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_add_stock_and_unit_choices'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PriceAlert',
        ),
    ]
