# Generated by Django 4.2.30 on 2026-04-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_unused_tables'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
