# Generated by Django 4.2.30 on 2026-05-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_stock_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='rut',
            field=models.CharField(blank=True, default='', max_length=12, verbose_name='RUT'),
        ),
    ]
